version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dostavanet2023  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  dostava-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Konjic1981
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - dostavanet2023

  rabbitmq-service:
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./eDostava.Subscriber/Dockerfile
      environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=guest
        - RABBITMQ_PASSWORD=guest
        - SMTP_SERVER=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_USERNAME=edostava9@gmail.com
        - SMTP_PASSWORD=rnkb bzps lqwl fuhs
        - API_HOST=localhost
        - API_PORT=7037
      depends_on:
        - rabbitmq
        - dostava-api
        - dostava-sql
      networks:
        - dostavanet2023


  dostava-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=dostava-sql,1433;Database=Dostava;User=sa;Password=Konjic1981;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=edostava9@gmail.com
      - SMTP_PASSWORD=rnkb bzps lqwl fuhs
    ports:
      - 7037:7037
    depends_on:
      - dostava-sql
    networks:
      - dostavanet2023

volumes:
  rabbitmq_data:

networks:
  dostavanet2023:
    driver: bridge
